### ISSUE TITLE
is this support for laravel 8 or below ?

### ISSUE THREAD

**Issue by zulfikar-ditya** [dionsaur84/lucid#1]
# support for laravel 8 or bellow

according in file composer.json is says require laravel 9 or above. my current project is using laravel 8.
```
    "require": {
        "doctrine/dbal": "^3.5",
        "laravel/framework": "^9.0"
    },
```

**Comment by dionsaur84** [comment]
i just removed the laravel version requirement, it should work for you now

**Comment by zulfikar-ditya** [comment]
thanks
